SELECT
O.ORDERID
,O.ORDERDATE
,O.SHIPDATE
,O.SHIPMODE
,O.CUSTOMERID
,O.PRODUCTID
,O.ORDERCOSTPRICE
,O.ORDERSELLINGPRICE
,(O.ORDERSELLINGPRICE-O.ORDERCOSTPRICE) AS ORDERPROFIT
,C.COUNTRY
,C.CUSTOMERNAME
,C.SEGMENT
,C.STATE
,P.CATEGORY
,P.PRODUCTNAME
,P.SUBCATEGORY
FROM {{ ref('raw_orders') }} as O
LEFT JOIN
{{ ref('raw_customer') }} as C
on O.CUSTOMERID=C.CUSTOMERID
LEFT JOIN {{ ref('raw_product') }} as P
on O.PRODUCTID=P.PRODUCTID